#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose-v2
  - sqlite3

runcmd:
  - systemctl enable --now docker
  - usermod -aG docker ubuntu
  - iptables -I INPUT 1 -p tcp --dport 80 -m state --state NEW -j ACCEPT
  - iptables -I INPUT 1 -p tcp --dport 443 -m state --state NEW -j ACCEPT
  - netfilter-persistent save
